version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.29.0-focal
    working_directory: ~/app
    steps:
      - checkout
      - run: npm i -D @playwright/test
      # - run: npx playwright install
      - run: npx playwright install --with-deps chromium
      # - run:
      #     name: "Install Dependencies"
      #     command: npm install
      # - run:
      #     name: "Install Playwright"
      #     command: npx playwright install --with-deps
      - run:
          name: "Run the test on BrowserStack"
          command: npm run bstack-parallel-browsers
          # command: npx playwright test e2e.spec.js --config=resources/conf/playwright-bstack.config.js --workers 2
workflows:
  build:
    jobs:
      - build