version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.29.0-focal
    working_directory: ~/app
    steps:
      - checkout
      - run: npm i extract-zip
      - run: npm i -D @playwright/test
      - run: npx playwright install chrome
      # - run:
      #     name: "Install Dependencies"
      #     command: npm install
      - run:
          name: Download BrowserStack Local binary and start it.
          command: |
            wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
            npx extract-zip BrowserStackLocal-linux-x64.zip
            ./BrowserStackLocal $BROWSERSTACK_ACCESS_KEY --daemon start
            npm run bstack-parallel-browsers
            ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY --daemon stop
          
          
      # - run:
      #     name: "Run the test on BrowserStack"
      #     command: npm run bstack-parallel-browsers
          # command: npx playwright test e2e.spec.js --config=resources/conf/playwright-bstack.config.js --workers 2
workflows:
  build:
    jobs:
      - build