version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.11.0
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: sudo npm install
      - run:
          name: "Install Playwright"
          command: npx playwright install-deps
      - run:
          name: "Run the test on BrowserStack"
          command: npx playwright test e2e.spec.js --config=resources/conf/playwright-bstack.config.js --workers 2
workflows:
  build:
    jobs:
      - build